"use client";
import { useEffect, useState, type FormEvent } from "react";
import Link from "next/link";
import { useSearchParams, useRouter } from "next/navigation";
import {
  verifyPasswordResetCode,
  confirmPasswordReset,
  signInWithEmailAndPassword,
  getMultiFactorResolver,
  type MultiFactorResolver,
  type MultiFactorError,
} from "firebase/auth";
import { firebaseAuth } from "@/lib/firebase/client";
import { completeSignIn } from "../login/completeSignIn";
import MfaChallenge from "../login/MfaChallenge";

const MIN_LENGTH = 8;

// Lands here from the emailed link generated by generatePasswordResetLink
// (src/lib/dal/passwordAuth.ts) — works identically whether this is a
// client's very first password (no credential existed yet) or a genuine
// forgot-password reset; Firebase doesn't distinguish the two cases.
export default function ResetPasswordForm() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const oobCode = searchParams.get("oobCode");

  const [status, setStatus] = useState<"checking" | "ready" | "invalid">(() => (oobCode ? "checking" : "invalid"));
  const [email, setEmail] = useState<string | null>(null);
  const [password, setPassword] = useState("");
  const [confirm, setConfirm] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [mfaResolver, setMfaResolver] = useState<MultiFactorResolver | null>(null);

  useEffect(() => {
    if (!oobCode) return;
    verifyPasswordResetCode(firebaseAuth, oobCode)
      .then((resolvedEmail) => {
        setEmail(resolvedEmail);
        setStatus("ready");
      })
      .catch(() => setStatus("invalid"));
  }, [oobCode]);

  function finish() {
    router.push("/");
    router.refresh();
  }

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setError(null);
    if (password.length < MIN_LENGTH) {
      setError(`Password must be at least ${MIN_LENGTH} characters.`);
      return;
    }
    if (password !== confirm) {
      setError("Passwords don't match.");
      return;
    }
    if (!oobCode || !email) return;

    setBusy(true);
    try {
      await confirmPasswordReset(firebaseAuth, oobCode, password);
      // Signs them straight in rather than bouncing back to a separate
      // login step — a freshly-set password is exactly what they'd type
      // there anyway.
      const result = await signInWithEmailAndPassword(firebaseAuth, email, password);
      const outcome = await completeSignIn(result.user);
      if (!outcome.ok) {
        setError(outcome.error);
        setBusy(false);
        return;
      }
      finish();
    } catch (err) {
      if (err && typeof err === "object" && "code" in err && err.code === "auth/multi-factor-auth-required") {
        setMfaResolver(getMultiFactorResolver(firebaseAuth, err as MultiFactorError));
        setBusy(false);
        return;
      }
      setError("Couldn't set your password. The link may have expired — request a new one from the login page.");
      setBusy(false);
    }
  }

  if (mfaResolver) {
    return <MfaChallenge resolver={mfaResolver} onSuccess={finish} onError={setError} />;
  }

  if (status === "checking") return null;

  if (status === "invalid") {
    return (
      <p style={{ color: "var(--gh-text-muted)", fontSize: "var(--gh-text-sm)", textAlign: "center" }}>
        This link isn&apos;t valid or has expired. Request a new one from the{" "}
        <Link href="/login" style={{ color: "var(--gh-accent)" }}>login page</Link>.
      </p>
    );
  }

  return (
    <form onSubmit={handleSubmit} style={{ width: "100%", display: "flex", flexDirection: "column", gap: "var(--gh-space-3)" }}>
      <p style={{ fontSize: "var(--gh-text-sm)", color: "var(--gh-text-muted)" }}>Setting a password for {email}</p>
      <input
        className="gh-input"
        type="password"
        value={password}
        onChange={(e) => setPassword(e.target.value)}
        placeholder={`New password (${MIN_LENGTH}+ characters)`}
        autoComplete="new-password"
        required
        minLength={MIN_LENGTH}
      />
      <input
        className="gh-input"
        type="password"
        value={confirm}
        onChange={(e) => setConfirm(e.target.value)}
        placeholder="Confirm password"
        autoComplete="new-password"
        required
        minLength={MIN_LENGTH}
      />
      <button className="gh-btn-primary" type="submit" disabled={busy} style={{ width: "100%", padding: "var(--gh-space-4)" }}>
        {busy ? "Setting password…" : "Set password"}
      </button>
      {error && (
        <p style={{ color: "var(--gh-danger)", fontSize: "var(--gh-text-sm)", textAlign: "center" }}>{error}</p>
      )}
    </form>
  );
}
